mesclics_admin_users:
    path: /
    defaults: { _controller: MesClicsUserBundle:Users:getUsers }

mesclics_admin_user:
    path: /{id}/
    defaults: { _controller: MesClicsUserBundle:Users:getUser }