services:
    #EVENT LISTENERS
    mesclics_user.doctrine_listener.user_creation:
        class: MesClics\UserBundle\Events\EventListeners\UserCreationListener
        # arguments:
        #     - "@mesclics_espace_client.client_numerator"
        #     - "@mesclics_utils.apis_manager"
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    mesclics_user.security_listener.interactive_login:
        class: MesClics\UserBundle\Events\EventListeners\UserInteractiveLoginListener
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@mesclics_navigation.navigator"
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: proceed }