<?php

namespace MC\UserBundle\Repository;

/**
 * ThumbnailFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThumbnailFileRepository extends \Doctrine\ORM\EntityRepository
{
}
